# Generated by Django 4.0.4 on 2022-06-25 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='live_database',
            fields=[
                ('tile_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tile_info', models.CharField(max_length=100)),
                ('last_visited', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='map_info',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=50)),
                ('user_map_name', models.CharField(max_length=50)),
                ('map_size', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='all_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=600)),
                ('tile_number', models.CharField(max_length=50)),
                ('tile_info', models.CharField(max_length=50)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.map_info')),
            ],
        ),
    ]
