# Generated by Django 4.0.4 on 2022-06-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mapi',
        ),
    ]
