# Generated by Django 4.0.4 on 2022-06-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_live_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live_database',
            name='order',
        ),
        migrations.AlterField(
            model_name='live_database',
            name='tile_num',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
