# Generated by Django 4.0.4 on 2022-05-31 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=600)),
                ('tile_number', models.IntegerField()),
                ('tile_info', models.CharField(max_length=50)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.map_info')),
            ],
        ),
    ]
