# Generated by Django 4.0.4 on 2022-06-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_map_info_map_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='live_database',
            fields=[
                ('tile_num', models.CharField(max_length=50)),
                ('tile_info', models.CharField(max_length=100)),
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('last_visited', models.BooleanField()),
            ],
        ),
    ]
