# Generated by Django 4.0.4 on 2022-05-30 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='map_info',
            fields=[
                ('map_id', models.IntegerField(primary_key=True, serialize=False)),
                ('map_size', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
